#!/bin/bash

# Railway Deployment Script for AI Chatbot
# This script helps you deploy your AI chatbot to Railway

echo "🚂 Railway Deployment Script for AI Chatbot"
echo "============================================="

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "❌ Railway CLI is not installed."
    echo "📥 Install it with: npm install -g @railway/cli"
    echo "🔗 Or visit: https://docs.railway.app/guides/cli"
    exit 1
fi

echo "✅ Railway CLI found"

# Check if user is logged in
if ! railway whoami &> /dev/null; then
    echo "🔐 Please log in to Railway first:"
    echo "   railway login"
    exit 1
fi

echo "✅ Railway authentication verified"

# Initialize project if not already done
if [ ! -f "railway.toml" ]; then
    echo "🎯 Initializing Railway project..."
    railway init
fi

echo "📋 Deployment Checklist:"
echo "========================"
echo "1. ✅ Dockerfile exists"
echo "2. ✅ package.json configured"
echo "3. ✅ railway.json created"
echo ""
echo "🔧 Required Environment Variables:"
echo "- AUTH_SECRET (generate with: openssl rand -base64 32)"
echo "- XAI_API_KEY (get from: https://console.x.ai/)"
echo "- POSTGRES_URL (will be auto-generated by Railway PostgreSQL addon)"
echo "- NEXT_PUBLIC_APP_URL (will be auto-generated by Railway)"
echo ""

read -p "🚀 Ready to deploy? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🚂 Deploying to Railway..."
    railway up
    echo ""
    echo "🎉 Deployment initiated!"
    echo "📱 Visit your Railway dashboard to:"
    echo "   - Add PostgreSQL database addon"
    echo "   - Set environment variables"
    echo "   - Monitor deployment progress"
    echo ""
    echo "🔗 Railway Dashboard: https://railway.app/dashboard"
else
    echo "❌ Deployment cancelled"
fi
